import { AIIcon, ForecastIcon, GlobeIcon } from "@/components/icons/FeatureIcons";
import Reveal from "@/components/Reveal";

const features = [
  {
    icon: ForecastIcon,
    title: "Agentic Cash Flow Forecasting",
    description:
      "Autonomous agents continuously model income volatility from transaction history, seasonal cycles, and local demand, surfacing liquidity gaps weeks before they hit.",
  },
  {
    icon: AIIcon,
    title: "XAI Risk Explanations",
    description:
      "Every risk score ships with a plain-language rationale generated by Gemini, so loan officers can defend decisions to auditors, regulators, and borrowers alike.",
  },
  {
    icon: GlobeIcon,
    title: "AlphaEarth Climate Monitoring",
    description:
      "Satellite-derived soil moisture, rainfall, and vegetation indices from Google AlphaEarth flag climate-driven default risk before it shows up in repayment data.",
  },
];

export default function Features() {
  return (
    <section id="features" className="py-20 sm:py-28">
      <div className="mx-auto w-full max-w-6xl px-6 lg:px-8">
        <Reveal className="mx-auto max-w-xl text-center">
          <h2 className="text-xs font-semibold uppercase tracking-[0.2em] text-lime-600">
            Platform
          </h2>
          <p className="mt-3 text-2xl font-semibold tracking-tight text-onyx sm:text-3xl">
            One platform, three ways to de-risk your portfolio
          </p>
        </Reveal>

        <div className="mt-12 grid grid-cols-1 gap-5 sm:grid-cols-2 lg:grid-cols-3">
          {features.map(({ icon: Icon, title, description }, i) => (
            <Reveal key={title} delay={i * 80}>
              <div className="group rounded-2xl border border-black/10 bg-white p-7 shadow-sm transition duration-300 hover:-translate-y-1 hover:shadow-lg">
                <div className="flex h-11 w-11 items-center justify-center rounded-full bg-lime-100 transition duration-300 group-hover:bg-lime-300">
                  <Icon className="h-5 w-5 text-lime-700" />
                </div>
                <h3 className="mt-6 text-base font-semibold text-onyx">
                  {title}
                </h3>
                <p className="mt-3 text-sm leading-6 text-onyx/60">
                  {description}
                </p>
              </div>
            </Reveal>
          ))}
        </div>
      </div>
    </section>
  );
}
