import {
  ArrowRight,
  Satellite,
  Sparkles,
  TrendingUp,
  Database,
  FileWarning,
  ClipboardList,
  Landmark,
  CheckCircle2,
} from "@/components/icons/MaterialIcons";
import Footer from "@/components/Footer";
import { AIIcon, ForecastIcon, GlobeIcon } from "@/components/icons/FeatureIcons";
import Navbar from "@/components/Navbar";

const features = [
  {
    icon: ForecastIcon,
    title: "Agentic Cash Flow Forecasting",
    description:
      "Autonomous agents continuously model income volatility from transaction history, seasonal cycles, and local demand, surfacing liquidity gaps weeks before they hit.",
  },
  {
    icon: AIIcon,
    title: "XAI Risk Explanations",
    description:
      "Every risk score ships with a plain-language rationale generated by Gemini, so loan officers can defend decisions to auditors, regulators, and borrowers alike.",
  },
  {
    icon: GlobeIcon,
    title: "AlphaEarth Climate Monitoring",
    description:
      "Satellite-derived soil moisture, rainfall, and vegetation indices from Google AlphaEarth flag climate-driven default risk before it shows up in repayment data.",
  },
];

const legacyPoints = [
  "Static credit bureau scores, updated quarterly at best",
  "No visibility into informal or cash-based income",
  "Blind to climate and weather shocks on repayment ability",
  "Risk flagged only after a payment is missed",
];

const gramosPoints = [
  "BigQuery-fused transaction logs, updated in real time",
  "Alternative data: mobile money, utility, and input purchases",
  "AlphaEarth satellite metrics on rainfall, soil, and vegetation",
  "Gemini reasoning flags risk 30+ days before default",
];

const stats = [
  { value: "30+ days", label: "Earlier detection" },
  { value: "2 sources", label: "BigQuery + AlphaEarth" },
  { value: "100%", label: "Explainable by Gemini" },
];

export default function Home() {
  return (
    <div id="top" className="flex flex-1 flex-col bg-paper text-onyx">
      <Chakra />
      <Flora />
      <Navbar />

      <main className="relative z-10 flex-1">
        {/* Hero */}
        <section className="relative overflow-hidden">
          <div className="relative mx-auto flex w-full max-w-3xl flex-col items-center px-6 py-20 text-center lg:px-8 lg:py-28">
            <span className="animate-rise inline-flex items-center rounded-full border border-black/10 bg-white px-4 py-1.5 text-xs font-medium uppercase tracking-[0.16em] text-onyx/40 shadow-sm">
              Built for rural credit risk
            </span>

            <h1
              className="animate-rise mt-6 max-w-2xl text-balance text-4xl font-normal leading-[1.2] tracking-[-0.03em] text-onyx sm:text-5xl sm:leading-[1.15]"
              style={{ animationDelay: "0.08s" }}
            >
              The AI Operating System for{" "}
              <span className="relative inline-block whitespace-nowrap">
                <svg
                  aria-hidden
                  viewBox="-8 0 320 46"
                  preserveAspectRatio="none"
                  className="animate-paint-stroke absolute -inset-x-3 inset-y-0 h-full w-[calc(100%+1.5rem)] origin-left"
                >
                  {/* under-layer, offset slightly for two-tone brush depth */}
                  <path
                    d="M9,17 L27,10 L47,15 L67,8 L91,13 L113,7 L137,12 L159,9 L181,14 L201,8 L219,13 L235,10 L249,16 L260,13 L253,26 L237,32 L221,28 L199,35 L177,30 L153,36 L129,32 L105,37 L81,33 L59,38 L37,33 L19,29 L11,23 Z"
                    fill="#65a30d"
                    fillOpacity="0.22"
                  />
                  {/* main stroke body — jagged torn edges, not a clean rectangle */}
                  <path
                    d="M6,15 L23,7 L44,12 L65,5 L88,11 L110,4 L134,10 L157,6 L179,12 L198,6 L217,11 L233,7 L246,13 L257,10 L249,23 L233,29 L217,25 L196,32 L175,27 L151,33 L127,29 L103,34 L79,30 L57,35 L35,30 L17,26 L8,21 Z"
                    fill="#bef264"
                  />
                  {/* dry-brush fraying at the trailing edge */}
                  <path
                    d="M257,10 L278,5 L266,14 L284,10"
                    stroke="#bef264"
                    strokeWidth="2.5"
                    strokeLinecap="round"
                    fill="none"
                    opacity="0.75"
                  />
                  <path
                    d="M253,20 L274,17 L262,24 L280,22"
                    stroke="#bef264"
                    strokeWidth="2"
                    strokeLinecap="round"
                    fill="none"
                    opacity="0.5"
                  />
                  <path
                    d="M247,28 L266,31 L256,35"
                    stroke="#bef264"
                    strokeWidth="1.5"
                    strokeLinecap="round"
                    fill="none"
                    opacity="0.35"
                  />
                  {/* paint flecks */}
                  <circle cx="290" cy="8" r="1.6" fill="#bef264" opacity="0.6" />
                  <circle cx="296" cy="15" r="1.2" fill="#84cc16" opacity="0.5" />
                  <circle cx="287" cy="21" r="1" fill="#bef264" opacity="0.4" />
                  <circle cx="298" cy="26" r="1.1" fill="#84cc16" opacity="0.35" />
                </svg>
                <span className="relative z-10 px-2 py-0.5">
                  Rural Financial Intelligence
                </span>
              </span>
            </h1>

            <p
              className="animate-rise mt-6 max-w-lg text-pretty text-base leading-7 text-onyx/60 sm:text-lg"
              style={{ animationDelay: "0.16s" }}
            >
              Predict NPA risk before it happens using climate satellite data
              and alternative transaction logs.
            </p>

            <div
              className="animate-rise mt-8 flex flex-col items-center gap-5 sm:flex-row"
              style={{ animationDelay: "0.24s" }}
            >
              <a
                href="#demo"
                className="inline-flex cursor-pointer items-center gap-2 rounded-full bg-lime-300 px-6 py-3 text-sm font-semibold text-onyx shadow-sm transition hover:-translate-y-0.5 hover:bg-lime-200 hover:shadow-md"
              >
                Request Demo
                <ArrowRight className="h-4 w-4" />
              </a>
              <a
                href="#architecture"
                className="inline-flex cursor-pointer items-center gap-1.5 text-sm font-medium text-onyx/70 transition hover:text-onyx"
              >
                See how it works
                <ArrowRight className="h-3.5 w-3.5" />
              </a>
            </div>

            {/* Stat cards */}
            <dl
              className="animate-rise mt-16 grid w-full grid-cols-3 gap-3 sm:gap-4"
              style={{ animationDelay: "0.32s" }}
            >
              {stats.map(({ value, label }) => (
                <div
                  key={label}
                  className="rounded-2xl border border-black/10 bg-white px-3 py-5 text-center shadow-sm transition hover:-translate-y-0.5 hover:shadow-md sm:px-5"
                >
                  <dd className="text-xl font-semibold tracking-tight text-onyx sm:text-2xl">
                    {value}
                  </dd>
                  <dt className="mt-1 text-[11px] uppercase tracking-wide text-onyx/45 sm:text-xs">
                    {label}
                  </dt>
                </div>
              ))}
            </dl>
          </div>
        </section>

        {/* Architecture */}
        <section id="architecture" className="py-20 sm:py-28">
          <div className="mx-auto w-full max-w-6xl px-6 lg:px-8">
            <div className="mx-auto max-w-xl text-center">
              <h2 className="text-xs font-semibold uppercase tracking-[0.2em] text-lime-600">
                Architecture
              </h2>
              <p className="mt-3 text-2xl font-semibold tracking-tight text-onyx sm:text-3xl">
                Legacy credit scoring can&rsquo;t see rural risk coming
              </p>
              <p className="mt-4 text-base leading-7 text-onyx/60">
                GramOS fuses structured transaction data with real-time earth
                observation, then reasons over both with Gemini.
              </p>
            </div>

            <div className="mt-12 grid grid-cols-1 gap-5 lg:grid-cols-2">
              {/* Legacy */}
              <div className="rounded-2xl border border-black/10 bg-white p-8 shadow-sm transition hover:shadow-md">
                <div className="flex items-center gap-3">
                  <div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-mist">
                    <Landmark className="h-4 w-4 text-onyx/40" />
                  </div>
                  <h3 className="text-sm font-medium uppercase tracking-widest text-onyx/40">
                    Legacy Scoring
                  </h3>
                </div>
                <ul className="mt-6 space-y-4">
                  {legacyPoints.map((point) => (
                    <li key={point} className="flex items-start gap-3">
                      <FileWarning className="mt-1 h-3.5 w-3.5 shrink-0 text-onyx/30" />
                      <span className="text-sm leading-6 text-onyx/60">
                        {point}
                      </span>
                    </li>
                  ))}
                </ul>
              </div>

              {/* GramOS */}
              <div className="rounded-2xl border border-lime-400/50 bg-white p-8 shadow-sm transition hover:shadow-md">
                <div className="flex items-center gap-3">
                  <div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-lime-100">
                    <Database className="h-4 w-4 text-lime-700" />
                  </div>
                  <h3 className="text-sm font-medium uppercase tracking-widest text-lime-700">
                    GramOS
                  </h3>
                </div>
                <ul className="mt-6 space-y-4">
                  {gramosPoints.map((point) => (
                    <li key={point} className="flex items-start gap-3">
                      <CheckCircle2 className="mt-1 h-3.5 w-3.5 shrink-0 text-lime-600" />
                      <span className="text-sm leading-6 text-onyx/80">
                        {point}
                      </span>
                    </li>
                  ))}
                </ul>
              </div>
            </div>

            {/* Pipeline strip */}
            <div className="mt-5 flex flex-col items-stretch justify-center gap-1 rounded-2xl border border-black/10 bg-white px-6 py-6 shadow-sm sm:flex-row sm:items-center sm:gap-0">
              <PipelineStep icon={ClipboardList} label="BigQuery Transaction Logs" />
              <PipelineArrow />
              <PipelineStep icon={Satellite} label="AlphaEarth Satellite Metrics" />
              <PipelineArrow />
              <PipelineStep
                icon={Sparkles}
                label="Gemini Reasoning Engine"
                highlight
              />
              <PipelineArrow />
              <PipelineStep icon={TrendingUp} label="Explainable Risk Score" />
            </div>
          </div>
        </section>

        {/* Features */}
        <section id="features" className="py-20 sm:py-28">
          <div className="mx-auto w-full max-w-6xl px-6 lg:px-8">
            <div className="mx-auto max-w-xl text-center">
              <h2 className="text-xs font-semibold uppercase tracking-[0.2em] text-lime-600">
                Platform
              </h2>
              <p className="mt-3 text-2xl font-semibold tracking-tight text-onyx sm:text-3xl">
                One platform, three ways to de-risk your portfolio
              </p>
            </div>

            <div className="mt-12 grid grid-cols-1 gap-5 sm:grid-cols-2 lg:grid-cols-3">
              {features.map(({ icon: Icon, title, description }) => (
                <div
                  key={title}
                  className="group rounded-2xl border border-black/10 bg-white p-7 shadow-sm transition duration-300 hover:-translate-y-1 hover:shadow-lg"
                >
                  <div className="flex h-11 w-11 items-center justify-center rounded-full bg-lime-100 transition duration-300 group-hover:bg-lime-300">
                    <Icon className="h-5 w-5 text-lime-700" />
                  </div>
                  <h3 className="mt-6 text-base font-semibold text-onyx">
                    {title}
                  </h3>
                  <p className="mt-3 text-sm leading-6 text-onyx/60">
                    {description}
                  </p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* CTA / Demo */}
        <section id="demo" className="border-t border-black/10 bg-mist">
          <div className="mx-auto flex w-full max-w-6xl flex-col items-center px-6 py-20 text-center sm:py-28 lg:px-8">
            <p className="text-xs font-semibold uppercase tracking-[0.2em] text-lime-600">
              Get started
            </p>
            <h2 className="mt-3 max-w-lg text-2xl font-semibold tracking-tight text-onyx sm:text-3xl">
              See GramOS flag risk in your portfolio
            </h2>
            <p className="mt-4 max-w-lg text-base leading-7 text-onyx/60">
              Book a walkthrough with our team and bring your own transaction
              sample, and we&rsquo;ll show you the explainable risk output live.
            </p>
            <a
              href="mailto:demo@gramos.ai"
              className="mt-8 inline-flex cursor-pointer items-center gap-2 rounded-full bg-lime-300 px-6 py-3 text-sm font-semibold text-onyx shadow-sm transition hover:-translate-y-0.5 hover:bg-lime-200 hover:shadow-md"
            >
              Request Demo
              <ArrowRight className="h-4 w-4" />
            </a>
          </div>
        </section>
      </main>

      <Footer />
    </div>
  );
}

function PipelineStep({
  icon: Icon,
  label,
  highlight = false,
}: {
  icon: typeof Sparkles;
  label: string;
  highlight?: boolean;
}) {
  return (
    <div className="flex flex-1 items-center justify-center gap-2.5 px-4 py-2 text-center">
      <Icon
        className={`h-4 w-4 shrink-0 ${
          highlight ? "text-lime-600" : "text-onyx/35"
        }`}
      />
      <span
        className={`text-xs font-medium uppercase tracking-wider ${
          highlight ? "text-lime-700" : "text-onyx/50"
        }`}
      >
        {label}
      </span>
    </div>
  );
}

function PipelineArrow() {
  return (
    <div aria-hidden className="mx-auto h-4 w-px bg-black/10 sm:h-px sm:w-8" />
  );
}

/** Ambient background motif: a lotus of leaf-shaped petals slow-spinning
 * around a rupee mark, pinned to the viewport (not the hero) so it stays
 * visible for the whole scroll. Sits in the right margin outside the
 * content column, behind everything (-z-10), pure CSS rotation. */
function Chakra() {
  const petalCount = 12;
  const petals = Array.from({ length: petalCount }, (_, i) => i);
  return (
    <div
      aria-hidden
      className="pointer-events-none fixed -right-56 top-28 z-0 hidden h-[40rem] w-[40rem] opacity-[0.4] xl:block"
    >
      <svg viewBox="0 0 400 400" className="animate-spin-slower h-full w-full">
        <circle
          cx="200"
          cy="200"
          r="192"
          fill="none"
          stroke="#65a30d"
          strokeOpacity="0.15"
          strokeWidth="1"
        />
        {petals.map((i) => {
          const angle = (i / petalCount) * 360;
          return (
            <path
              key={i}
              d="M200,145 C182,110 182,60 200,32 C218,60 218,110 200,145 Z"
              fill="#84cc16"
              fillOpacity={i % 2 === 0 ? "0.14" : "0.07"}
              stroke="#4d7c0f"
              strokeOpacity="0.3"
              strokeWidth="1"
              transform={`rotate(${angle} 200 200)`}
            />
          );
        })}
        <circle
          cx="200"
          cy="200"
          r="36"
          fill="#fafaf6"
          stroke="#65a30d"
          strokeOpacity="0.4"
          strokeWidth="1"
        />
        <text
          x="200"
          y="212"
          textAnchor="middle"
          fontSize="32"
          fontWeight="600"
          fill="#4d7c0f"
          fillOpacity="0.6"
        >
          ₹
        </text>
      </svg>
    </div>
  );
}

/** Ambient background motif for the left margin, balancing the Chakra on
 * the right: grass, a sugarcane stalk with its plume, and a maize stalk
 * with a cob, each swaying independently like wind. Fixed to the viewport
 * (not the hero) so it's visible for the whole scroll. */
function Flora() {
  const flowers = [
    { cx: 55, cy: 468 },
    { cx: 102, cy: 458 },
  ];

  const rightFlowers = [
    { cx: 193, cy: 480 },
    { cx: 224, cy: 468 },
  ];

  return (
    <div
      aria-hidden
      className="pointer-events-none fixed -left-20 bottom-0 z-0 hidden h-[30rem] w-64 opacity-[0.4] xl:block"
    >
      <svg viewBox="0 0 260 520" className="h-full w-full">
        {/* Grass */}
        <g
          className="animate-sway"
          style={{ transformOrigin: "68px 500px", animationDelay: "-1s" }}
        >
          {[
            "M20,500 Q10,460 14,420",
            "M45,500 Q55,440 40,380",
            "M70,500 Q60,470 68,440",
            "M95,500 Q105,450 92,390",
            "M115,500 Q108,470 118,430",
          ].map((d, i) => (
            <path
              key={i}
              d={d}
              fill="none"
              stroke="#4d7c0f"
              strokeOpacity={i % 2 === 0 ? "0.4" : "0.25"}
              strokeWidth="3"
              strokeLinecap="round"
            />
          ))}
        </g>

        {/* Small flowers */}
        {flowers.map(({ cx, cy }, fi) => (
          <g key={fi}>
            {Array.from({ length: 5 }, (_, i) => (
              <ellipse
                key={i}
                cx={cx}
                cy={cy - 7}
                rx="6"
                ry="3"
                fill="#bef264"
                fillOpacity="0.35"
                transform={`rotate(${(i / 5) * 360} ${cx} ${cy})`}
              />
            ))}
            <circle cx={cx} cy={cy} r="2.5" fill="#4d7c0f" fillOpacity="0.5" />
          </g>
        ))}

        {/* Sugarcane */}
        <g
          className="animate-sway-slow"
          style={{ transformOrigin: "170px 500px", animationDelay: "-2.5s" }}
        >
          <path
            d="M170,500 L170,140"
            stroke="#4d7c0f"
            strokeOpacity="0.4"
            strokeWidth="5"
            strokeLinecap="round"
          />
          {[460, 420, 380, 340, 300, 260, 220, 180].map((y) => (
            <path
              key={y}
              d={`M162,${y} L178,${y}`}
              stroke="#4d7c0f"
              strokeOpacity="0.3"
              strokeWidth="2.5"
              strokeLinecap="round"
            />
          ))}
          {[
            "M170,140 Q150,100 130,75",
            "M170,140 Q160,95 145,65",
            "M170,140 Q168,90 160,55",
            "M170,140 Q170,85 170,50",
            "M170,140 Q172,90 180,55",
            "M170,140 Q180,95 195,65",
            "M170,140 Q190,100 210,75",
          ].map((d, i) => (
            <path
              key={i}
              d={d}
              fill="none"
              stroke="#84cc16"
              strokeOpacity="0.4"
              strokeWidth="2"
              strokeLinecap="round"
            />
          ))}
        </g>

        {/* Small flowers, right side of the cane */}
        {rightFlowers.map(({ cx, cy }, fi) => (
          <g key={fi}>
            {Array.from({ length: 5 }, (_, i) => (
              <ellipse
                key={i}
                cx={cx}
                cy={cy - 7}
                rx="6"
                ry="3"
                fill="#bef264"
                fillOpacity="0.35"
                transform={`rotate(${(i / 5) * 360} ${cx} ${cy})`}
              />
            ))}
            <circle cx={cx} cy={cy} r="2.5" fill="#4d7c0f" fillOpacity="0.5" />
          </g>
        ))}

        {/* Maize */}
        <g
          className="animate-sway"
          style={{ transformOrigin: "210px 500px", animationDelay: "-0.3s" }}
        >
          <path
            d="M210,500 L210,220"
            stroke="#4d7c0f"
            strokeOpacity="0.4"
            strokeWidth="5"
            strokeLinecap="round"
          />
          <path
            d="M210,380 C185,360 170,320 175,280 C195,300 212,340 210,380 Z"
            fill="#84cc16"
            fillOpacity="0.14"
            stroke="#4d7c0f"
            strokeOpacity="0.3"
            strokeWidth="1"
          />
          <path
            d="M210,300 C235,280 250,240 245,200 C225,220 208,260 210,300 Z"
            fill="#84cc16"
            fillOpacity="0.14"
            stroke="#4d7c0f"
            strokeOpacity="0.3"
            strokeWidth="1"
          />
          <ellipse
            cx="226"
            cy="345"
            rx="10"
            ry="24"
            fill="#bef264"
            fillOpacity="0.2"
            stroke="#4d7c0f"
            strokeOpacity="0.35"
            strokeWidth="1"
            transform="rotate(12 226 345)"
          />
          {[
            "M210,220 Q200,200 195,185",
            "M210,220 Q210,195 210,175",
            "M210,220 Q220,200 225,185",
          ].map((d, i) => (
            <path
              key={i}
              d={d}
              fill="none"
              stroke="#84cc16"
              strokeOpacity="0.4"
              strokeWidth="2"
              strokeLinecap="round"
            />
          ))}
        </g>
      </svg>
    </div>
  );
}
