import {
  ArrowRight,
  Satellite,
  Sparkles,
  TrendingUp,
  Database,
  FileWarning,
  ClipboardList,
  Landmark,
  CheckCircle2,
} from "@/components/icons/MaterialIcons";
import Footer from "@/components/Footer";
import { AIIcon, ForecastIcon, GlobeIcon } from "@/components/icons/FeatureIcons";
import Navbar from "@/components/Navbar";

const features = [
  {
    icon: ForecastIcon,
    title: "Agentic Cash Flow Forecasting",
    description:
      "Autonomous agents continuously model income volatility from transaction history, seasonal cycles, and local demand, surfacing liquidity gaps weeks before they hit.",
  },
  {
    icon: AIIcon,
    title: "XAI Risk Explanations",
    description:
      "Every risk score ships with a plain-language rationale generated by Gemini, so loan officers can defend decisions to auditors, regulators, and borrowers alike.",
  },
  {
    icon: GlobeIcon,
    title: "AlphaEarth Climate Monitoring",
    description:
      "Satellite-derived soil moisture, rainfall, and vegetation indices from Google AlphaEarth flag climate-driven default risk before it shows up in repayment data.",
  },
];

const legacyPoints = [
  "Static credit bureau scores, updated quarterly at best",
  "No visibility into informal or cash-based income",
  "Blind to climate and weather shocks on repayment ability",
  "Risk flagged only after a payment is missed",
];

const gramosPoints = [
  "BigQuery-fused transaction logs, updated in real time",
  "Alternative data: mobile money, utility, and input purchases",
  "AlphaEarth satellite metrics on rainfall, soil, and vegetation",
  "Gemini reasoning flags risk 30+ days before default",
];

const stats = [
  { value: "30+ days", label: "Earlier risk detection" },
  { value: "BigQuery + AlphaEarth", label: "Data sources fused" },
  { value: "Explainable", label: "Every score, by Gemini" },
];

export default function Home() {
  return (
    <div id="top" className="flex flex-1 flex-col bg-onyx text-slate-50">
      <Navbar />

      <main className="flex-1">
        {/* Hero */}
        <section className="relative overflow-hidden">
          <div aria-hidden className="pointer-events-none absolute inset-0 overflow-hidden">
            <div className="animate-aurora absolute left-1/2 top-[-12%] h-[34rem] w-[34rem] -translate-x-1/2 rounded-full bg-amber-400/20 blur-[130px]" />
            <div
              className="animate-aurora absolute right-[8%] top-[26%] h-[22rem] w-[22rem] rounded-full bg-amber-300/10 blur-[110px]"
              style={{ animationDelay: "-9s" }}
            />
          </div>

          <div className="relative mx-auto flex w-full max-w-5xl flex-col items-center px-6 py-32 text-center lg:px-8 lg:py-44">
            <span className="animate-rise inline-flex items-center rounded-full border border-gray-800 px-4 py-1.5 text-xs font-medium uppercase tracking-widest text-slate-400">
              Built for rural credit risk
            </span>

            <h1
              className="animate-rise mt-8 max-w-4xl text-balance text-5xl font-semibold tracking-tight text-slate-50 sm:text-6xl lg:text-7xl"
              style={{ animationDelay: "0.08s" }}
            >
              The AI Operating System for{" "}
              <span className="text-amber-400">Rural Financial Intelligence</span>
            </h1>

            <p
              className="animate-rise mt-8 max-w-xl text-pretty text-lg font-light leading-8 text-slate-400"
              style={{ animationDelay: "0.16s" }}
            >
              Predict NPA risk before it happens using climate satellite data
              and alternative transaction logs.
            </p>

            <div
              className="animate-rise mt-12 flex flex-col items-center gap-6 sm:flex-row"
              style={{ animationDelay: "0.24s" }}
            >
              <a
                href="#demo"
                className="inline-flex cursor-pointer items-center gap-2 rounded-full bg-amber-400 px-7 py-3.5 text-sm font-semibold text-onyx transition hover:bg-amber-300"
              >
                Request Demo
                <ArrowRight className="h-4 w-4" />
              </a>
              <a
                href="#architecture"
                className="inline-flex cursor-pointer items-center gap-1.5 text-sm font-medium text-slate-300 transition hover:text-amber-400"
              >
                See how it works
                <ArrowRight className="h-3.5 w-3.5" />
              </a>
            </div>

            {/* Stat strip */}
            <dl
              className="animate-rise mt-24 grid w-full max-w-3xl grid-cols-1 divide-y divide-gray-800 border-t border-gray-800 sm:grid-cols-3 sm:divide-x sm:divide-y-0"
              style={{ animationDelay: "0.32s" }}
            >
              {stats.map(({ value, label }) => (
                <div key={label} className="px-6 py-8 text-center">
                  <dd className="text-3xl font-light tracking-tight text-slate-50 sm:text-4xl">
                    {value}
                  </dd>
                  <dt className="mt-2 text-xs uppercase tracking-widest text-slate-500">
                    {label}
                  </dt>
                </div>
              ))}
            </dl>
          </div>
        </section>

        {/* Architecture */}
        <section id="architecture" className="py-32 sm:py-40">
          <div className="mx-auto w-full max-w-6xl px-6 lg:px-8">
            <div className="mx-auto max-w-2xl text-center">
              <h2 className="text-xs font-semibold uppercase tracking-[0.2em] text-amber-400">
                Architecture
              </h2>
              <p className="mt-4 text-3xl font-semibold tracking-tight text-slate-50 sm:text-5xl">
                Legacy credit scoring can&rsquo;t see rural risk coming
              </p>
              <p className="mt-6 text-lg font-light leading-8 text-slate-400">
                GramOS fuses structured transaction data with real-time earth
                observation, then reasons over both with Gemini.
              </p>
            </div>

            <div className="mt-20 grid grid-cols-1 gap-6 lg:grid-cols-2">
              {/* Legacy */}
              <div className="rounded-3xl border border-gray-800 p-10 lg:p-12">
                <div className="flex items-center gap-4">
                  <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full border border-gray-800">
                    <Landmark className="h-4 w-4 text-slate-500" />
                  </div>
                  <h3 className="text-sm font-medium uppercase tracking-widest text-slate-500">
                    Legacy Scoring
                  </h3>
                </div>
                <ul className="mt-8 space-y-5">
                  {legacyPoints.map((point) => (
                    <li key={point} className="flex items-start gap-3">
                      <FileWarning className="mt-1 h-3.5 w-3.5 shrink-0 text-slate-600" />
                      <span className="text-sm leading-7 text-slate-400">
                        {point}
                      </span>
                    </li>
                  ))}
                </ul>
              </div>

              {/* GramOS */}
              <div className="rounded-3xl border border-amber-400/40 p-10 lg:p-12">
                <div className="flex items-center gap-4">
                  <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full border border-amber-400/40">
                    <Database className="h-4 w-4 text-amber-400" />
                  </div>
                  <h3 className="text-sm font-medium uppercase tracking-widest text-amber-400">
                    GramOS
                  </h3>
                </div>
                <ul className="mt-8 space-y-5">
                  {gramosPoints.map((point) => (
                    <li key={point} className="flex items-start gap-3">
                      <CheckCircle2 className="mt-1 h-3.5 w-3.5 shrink-0 text-amber-400" />
                      <span className="text-sm leading-7 text-slate-300">
                        {point}
                      </span>
                    </li>
                  ))}
                </ul>
              </div>
            </div>

            {/* Pipeline strip */}
            <div className="mt-8 flex flex-col items-stretch justify-center gap-1 rounded-3xl border border-gray-800 px-6 py-8 sm:flex-row sm:items-center sm:gap-0">
              <PipelineStep icon={ClipboardList} label="BigQuery Transaction Logs" />
              <PipelineArrow />
              <PipelineStep icon={Satellite} label="AlphaEarth Satellite Metrics" />
              <PipelineArrow />
              <PipelineStep
                icon={Sparkles}
                label="Gemini Reasoning Engine"
                highlight
              />
              <PipelineArrow />
              <PipelineStep icon={TrendingUp} label="Explainable Risk Score" />
            </div>
          </div>
        </section>

        {/* Features */}
        <section id="features" className="py-32 sm:py-40">
          <div className="mx-auto w-full max-w-6xl px-6 lg:px-8">
            <div className="mx-auto max-w-2xl text-center">
              <h2 className="text-xs font-semibold uppercase tracking-[0.2em] text-amber-400">
                Platform
              </h2>
              <p className="mt-4 text-3xl font-semibold tracking-tight text-slate-50 sm:text-5xl">
                One platform, three ways to de-risk your portfolio
              </p>
            </div>

            <div className="mt-20 grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3">
              {features.map(({ icon: Icon, title, description }) => (
                <div
                  key={title}
                  className="group rounded-3xl border border-gray-800 p-10 transition-colors duration-300 hover:border-amber-400/40"
                >
                  <div className="flex h-12 w-12 items-center justify-center rounded-full border border-gray-800 transition-colors duration-300 group-hover:border-amber-400/60">
                    <Icon className="h-5 w-5 text-amber-400" />
                  </div>
                  <h3 className="mt-8 text-lg font-semibold text-slate-50">
                    {title}
                  </h3>
                  <p className="mt-4 text-sm font-light leading-7 text-slate-400">
                    {description}
                  </p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* CTA / Demo */}
        <section id="demo" className="border-t border-gray-800">
          <div className="mx-auto flex w-full max-w-6xl flex-col items-center px-6 py-32 text-center sm:py-40 lg:px-8">
            <p className="text-xs font-semibold uppercase tracking-[0.2em] text-amber-400">
              Get started
            </p>
            <h2 className="mt-4 max-w-xl text-3xl font-semibold tracking-tight text-slate-50 sm:text-5xl">
              See GramOS flag risk in your portfolio
            </h2>
            <p className="mt-6 max-w-xl text-lg font-light leading-8 text-slate-400">
              Book a walkthrough with our team and bring your own transaction
              sample, and we&rsquo;ll show you the explainable risk output live.
            </p>
            <a
              href="mailto:demo@gramos.ai"
              className="mt-10 inline-flex cursor-pointer items-center gap-2 rounded-full bg-amber-400 px-7 py-3.5 text-sm font-semibold text-onyx transition hover:bg-amber-300"
            >
              Request Demo
              <ArrowRight className="h-4 w-4" />
            </a>
          </div>
        </section>
      </main>

      <Footer />
    </div>
  );
}

function PipelineStep({
  icon: Icon,
  label,
  highlight = false,
}: {
  icon: typeof Sparkles;
  label: string;
  highlight?: boolean;
}) {
  return (
    <div className="flex flex-1 items-center justify-center gap-2.5 px-4 py-2 text-center">
      <Icon
        className={`h-4 w-4 shrink-0 ${
          highlight ? "text-amber-400" : "text-slate-600"
        }`}
      />
      <span
        className={`text-xs font-medium uppercase tracking-wider ${
          highlight ? "text-amber-400" : "text-slate-500"
        }`}
      >
        {label}
      </span>
    </div>
  );
}

function PipelineArrow() {
  return (
    <div
      aria-hidden
      className="mx-auto h-4 w-px bg-gray-800 sm:h-px sm:w-8"
    />
  );
}
