import {
  ArrowRight,
  Satellite,
  Sparkles,
  TrendingUp,
  Database,
  FileWarning,
  ClipboardList,
  Landmark,
  CheckCircle2,
} from "@/components/icons/MaterialIcons";
import Footer from "@/components/Footer";
import { AIIcon, ForecastIcon, GlobeIcon } from "@/components/icons/FeatureIcons";
import Navbar from "@/components/Navbar";

const features = [
  {
    icon: ForecastIcon,
    title: "Agentic Cash Flow Forecasting",
    description:
      "Autonomous agents continuously model income volatility from transaction history, seasonal cycles, and local demand, surfacing liquidity gaps weeks before they hit.",
  },
  {
    icon: AIIcon,
    title: "XAI Risk Explanations",
    description:
      "Every risk score ships with a plain-language rationale generated by Gemini, so loan officers can defend decisions to auditors, regulators, and borrowers alike.",
  },
  {
    icon: GlobeIcon,
    title: "AlphaEarth Climate Monitoring",
    description:
      "Satellite-derived soil moisture, rainfall, and vegetation indices from Google AlphaEarth flag climate-driven default risk before it shows up in repayment data.",
  },
];

const legacyPoints = [
  "Static credit bureau scores, updated quarterly at best",
  "No visibility into informal or cash-based income",
  "Blind to climate and weather shocks on repayment ability",
  "Risk flagged only after a payment is missed",
];

const gramosPoints = [
  "BigQuery-fused transaction logs, updated in real time",
  "Alternative data: mobile money, utility, and input purchases",
  "AlphaEarth satellite metrics on rainfall, soil, and vegetation",
  "Gemini reasoning flags risk 30+ days before default",
];

const stats = [
  { value: "30+ days", label: "Earlier detection" },
  { value: "2 sources", label: "BigQuery + AlphaEarth" },
  { value: "100%", label: "Explainable by Gemini" },
];

export default function Home() {
  return (
    <div id="top" className="flex flex-1 flex-col bg-paper text-onyx">
      <Chakra />
      <Navbar />

      <main className="relative z-10 flex-1">
        {/* Hero */}
        <section className="relative overflow-hidden">
          <div className="relative mx-auto flex w-full max-w-3xl flex-col items-center px-6 py-20 text-center lg:px-8 lg:py-28">
            <span className="animate-rise inline-flex items-center rounded-full border border-black/10 bg-white px-4 py-1.5 text-xs font-medium uppercase tracking-widest text-onyx/50 shadow-sm">
              Built for rural credit risk
            </span>

            <h1
              className="animate-rise mt-6 max-w-2xl text-balance text-4xl font-semibold leading-[1.35] tracking-tight text-onyx sm:text-5xl sm:leading-[1.3]"
              style={{ animationDelay: "0.08s" }}
            >
              The AI Operating System for{" "}
              <span className="inline-block rounded-lg bg-lime-300 px-2 py-0.5">
                Rural Financial Intelligence
              </span>
            </h1>

            <p
              className="animate-rise mt-6 max-w-lg text-pretty text-base leading-7 text-onyx/60 sm:text-lg"
              style={{ animationDelay: "0.16s" }}
            >
              Predict NPA risk before it happens using climate satellite data
              and alternative transaction logs.
            </p>

            <div
              className="animate-rise mt-8 flex flex-col items-center gap-5 sm:flex-row"
              style={{ animationDelay: "0.24s" }}
            >
              <a
                href="#demo"
                className="inline-flex cursor-pointer items-center gap-2 rounded-full bg-lime-300 px-6 py-3 text-sm font-semibold text-onyx shadow-sm transition hover:-translate-y-0.5 hover:bg-lime-200 hover:shadow-md"
              >
                Request Demo
                <ArrowRight className="h-4 w-4" />
              </a>
              <a
                href="#architecture"
                className="inline-flex cursor-pointer items-center gap-1.5 text-sm font-medium text-onyx/70 transition hover:text-onyx"
              >
                See how it works
                <ArrowRight className="h-3.5 w-3.5" />
              </a>
            </div>

            {/* Stat cards */}
            <dl
              className="animate-rise mt-16 grid w-full grid-cols-3 gap-3 sm:gap-4"
              style={{ animationDelay: "0.32s" }}
            >
              {stats.map(({ value, label }) => (
                <div
                  key={label}
                  className="rounded-2xl border border-black/10 bg-white px-3 py-5 text-center shadow-sm transition hover:-translate-y-0.5 hover:shadow-md sm:px-5"
                >
                  <dd className="text-xl font-semibold tracking-tight text-onyx sm:text-2xl">
                    {value}
                  </dd>
                  <dt className="mt-1 text-[11px] uppercase tracking-wide text-onyx/45 sm:text-xs">
                    {label}
                  </dt>
                </div>
              ))}
            </dl>
          </div>
        </section>

        {/* Architecture */}
        <section id="architecture" className="py-20 sm:py-28">
          <div className="mx-auto w-full max-w-6xl px-6 lg:px-8">
            <div className="mx-auto max-w-xl text-center">
              <h2 className="text-xs font-semibold uppercase tracking-[0.2em] text-lime-600">
                Architecture
              </h2>
              <p className="mt-3 text-2xl font-semibold tracking-tight text-onyx sm:text-3xl">
                Legacy credit scoring can&rsquo;t see rural risk coming
              </p>
              <p className="mt-4 text-base leading-7 text-onyx/60">
                GramOS fuses structured transaction data with real-time earth
                observation, then reasons over both with Gemini.
              </p>
            </div>

            <div className="mt-12 grid grid-cols-1 gap-5 lg:grid-cols-2">
              {/* Legacy */}
              <div className="rounded-2xl border border-black/10 bg-white p-8 shadow-sm transition hover:shadow-md">
                <div className="flex items-center gap-3">
                  <div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-mist">
                    <Landmark className="h-4 w-4 text-onyx/40" />
                  </div>
                  <h3 className="text-sm font-medium uppercase tracking-widest text-onyx/40">
                    Legacy Scoring
                  </h3>
                </div>
                <ul className="mt-6 space-y-4">
                  {legacyPoints.map((point) => (
                    <li key={point} className="flex items-start gap-3">
                      <FileWarning className="mt-1 h-3.5 w-3.5 shrink-0 text-onyx/30" />
                      <span className="text-sm leading-6 text-onyx/60">
                        {point}
                      </span>
                    </li>
                  ))}
                </ul>
              </div>

              {/* GramOS */}
              <div className="rounded-2xl border border-lime-400/50 bg-white p-8 shadow-sm transition hover:shadow-md">
                <div className="flex items-center gap-3">
                  <div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-lime-100">
                    <Database className="h-4 w-4 text-lime-700" />
                  </div>
                  <h3 className="text-sm font-medium uppercase tracking-widest text-lime-700">
                    GramOS
                  </h3>
                </div>
                <ul className="mt-6 space-y-4">
                  {gramosPoints.map((point) => (
                    <li key={point} className="flex items-start gap-3">
                      <CheckCircle2 className="mt-1 h-3.5 w-3.5 shrink-0 text-lime-600" />
                      <span className="text-sm leading-6 text-onyx/80">
                        {point}
                      </span>
                    </li>
                  ))}
                </ul>
              </div>
            </div>

            {/* Pipeline strip */}
            <div className="mt-5 flex flex-col items-stretch justify-center gap-1 rounded-2xl border border-black/10 bg-white px-6 py-6 shadow-sm sm:flex-row sm:items-center sm:gap-0">
              <PipelineStep icon={ClipboardList} label="BigQuery Transaction Logs" />
              <PipelineArrow />
              <PipelineStep icon={Satellite} label="AlphaEarth Satellite Metrics" />
              <PipelineArrow />
              <PipelineStep
                icon={Sparkles}
                label="Gemini Reasoning Engine"
                highlight
              />
              <PipelineArrow />
              <PipelineStep icon={TrendingUp} label="Explainable Risk Score" />
            </div>
          </div>
        </section>

        {/* Features */}
        <section id="features" className="py-20 sm:py-28">
          <div className="mx-auto w-full max-w-6xl px-6 lg:px-8">
            <div className="mx-auto max-w-xl text-center">
              <h2 className="text-xs font-semibold uppercase tracking-[0.2em] text-lime-600">
                Platform
              </h2>
              <p className="mt-3 text-2xl font-semibold tracking-tight text-onyx sm:text-3xl">
                One platform, three ways to de-risk your portfolio
              </p>
            </div>

            <div className="mt-12 grid grid-cols-1 gap-5 sm:grid-cols-2 lg:grid-cols-3">
              {features.map(({ icon: Icon, title, description }) => (
                <div
                  key={title}
                  className="group rounded-2xl border border-black/10 bg-white p-7 shadow-sm transition duration-300 hover:-translate-y-1 hover:shadow-lg"
                >
                  <div className="flex h-11 w-11 items-center justify-center rounded-full bg-lime-100 transition duration-300 group-hover:bg-lime-300">
                    <Icon className="h-5 w-5 text-lime-700" />
                  </div>
                  <h3 className="mt-6 text-base font-semibold text-onyx">
                    {title}
                  </h3>
                  <p className="mt-3 text-sm leading-6 text-onyx/60">
                    {description}
                  </p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* CTA / Demo */}
        <section id="demo" className="border-t border-black/10 bg-mist">
          <div className="mx-auto flex w-full max-w-6xl flex-col items-center px-6 py-20 text-center sm:py-28 lg:px-8">
            <p className="text-xs font-semibold uppercase tracking-[0.2em] text-lime-600">
              Get started
            </p>
            <h2 className="mt-3 max-w-lg text-2xl font-semibold tracking-tight text-onyx sm:text-3xl">
              See GramOS flag risk in your portfolio
            </h2>
            <p className="mt-4 max-w-lg text-base leading-7 text-onyx/60">
              Book a walkthrough with our team and bring your own transaction
              sample, and we&rsquo;ll show you the explainable risk output live.
            </p>
            <a
              href="mailto:demo@gramos.ai"
              className="mt-8 inline-flex cursor-pointer items-center gap-2 rounded-full bg-lime-300 px-6 py-3 text-sm font-semibold text-onyx shadow-sm transition hover:-translate-y-0.5 hover:bg-lime-200 hover:shadow-md"
            >
              Request Demo
              <ArrowRight className="h-4 w-4" />
            </a>
          </div>
        </section>
      </main>

      <Footer />
    </div>
  );
}

function PipelineStep({
  icon: Icon,
  label,
  highlight = false,
}: {
  icon: typeof Sparkles;
  label: string;
  highlight?: boolean;
}) {
  return (
    <div className="flex flex-1 items-center justify-center gap-2.5 px-4 py-2 text-center">
      <Icon
        className={`h-4 w-4 shrink-0 ${
          highlight ? "text-lime-600" : "text-onyx/35"
        }`}
      />
      <span
        className={`text-xs font-medium uppercase tracking-wider ${
          highlight ? "text-lime-700" : "text-onyx/50"
        }`}
      >
        {label}
      </span>
    </div>
  );
}

function PipelineArrow() {
  return (
    <div aria-hidden className="mx-auto h-4 w-px bg-black/10 sm:h-px sm:w-8" />
  );
}

/** Ambient background motif: a lotus of leaf-shaped petals slow-spinning
 * around a rupee mark, pinned to the viewport (not the hero) so it stays
 * visible for the whole scroll. Sits in the right margin outside the
 * content column, behind everything (-z-10), pure CSS rotation. */
function Chakra() {
  const petalCount = 12;
  const petals = Array.from({ length: petalCount }, (_, i) => i);
  return (
    <div
      aria-hidden
      className="pointer-events-none fixed -right-56 top-28 z-0 hidden h-[40rem] w-[40rem] opacity-[0.4] xl:block"
    >
      <svg viewBox="0 0 400 400" className="animate-spin-slower h-full w-full">
        <circle
          cx="200"
          cy="200"
          r="192"
          fill="none"
          stroke="#65a30d"
          strokeOpacity="0.15"
          strokeWidth="1"
        />
        {petals.map((i) => {
          const angle = (i / petalCount) * 360;
          return (
            <path
              key={i}
              d="M200,145 C182,110 182,60 200,32 C218,60 218,110 200,145 Z"
              fill="#84cc16"
              fillOpacity={i % 2 === 0 ? "0.14" : "0.07"}
              stroke="#4d7c0f"
              strokeOpacity="0.3"
              strokeWidth="1"
              transform={`rotate(${angle} 200 200)`}
            />
          );
        })}
        <circle
          cx="200"
          cy="200"
          r="36"
          fill="#fafaf6"
          stroke="#65a30d"
          strokeOpacity="0.4"
          strokeWidth="1"
        />
        <text
          x="200"
          y="212"
          textAnchor="middle"
          fontSize="32"
          fontWeight="600"
          fill="#4d7c0f"
          fillOpacity="0.6"
        >
          ₹
        </text>
      </svg>
    </div>
  );
}
